[package]
name = "newtypes"
version = "0.1.0"
authors = ["coco <coco@hexgolems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_derive = "*"
clap = "2"
snafu="0.6.0"
nix="0.15.0"
ron="0.6.0"